easy_admin:

   entities:
       # List the entity class name you want to manage
    Categories:
        class: App\Entity\Categories
        form:
            fields:
                - {property: 'nom'}


    Produits:     
        class: App\Entity\Produits     